function export_v2_diagram()
% Native Simulink renderings for review of control-theory readability.
here=fileparts(mfilename('fullpath'));
load_system(fullfile(fileparts(here),'V2.slx'));
views={'V2','V2_top_level'; ...
    'V2/Position Controller','V2_position'; ...
    'V2/Velocity Controller','V2_velocity'; ...
    'V2/Attitude Controller','V2_attitude'; ...
    'V2/Rate Controller + DOB','V2_rate_dob'; ...
    'V2/Rate Controller + DOB/Conventional DOB','V2_dob'; ...
    'V2/Rate Controller + DOB/Rate PID','V2_pid'; ...
    'V2/CoM Estimator','V2_moce'; ...
    'V2/Monitoring','V2_monitoring'};
for k=1:size(views,1)
    set_param(views{k,1},'PaperOrientation','landscape','PaperType','A3','PaperPositionMode','auto');
    print(['-s' views{k,1}],'-dpng','-r120',fullfile(here,[views{k,2} '.png']));
end
end
